name: table_health
version: "0.1.0"
config-version: 2
profile: table_health

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  table_health:
    bronze:
      +schema: bronze
      +materialized: table
